#!/bin/sh
cd ~/tools-odoo/toggl_to_odoo/
echo "Uploading T.S."
datetime=$(date -d "now - 14 days" +%Y-%m-%d)
echo "On odoo.com"
python3 -m toggl_to_odoo upload -ds "$datetime" -te project-tool --merge -u cydu -p $(gnome-keyring-query get odoo) toggl2odoo https://www.odoo.com openerp history.log
echo "On project-tool"
python3 -m toggl_to_odoo upload -ds "$datetime" -ti project-tool --merge -u cydu@odoo.com -p $(gnome-keyring-query get odoo) toggl2odoo https://project-tool.odoo.com  odoo-ps-psbe-large-project-tool-14-0-master-1964163 history-project-tool
echo "Done uploading"
read
exit 0
